# Generated by Django 5.1.6 on 2025-03-02 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dateofbirth', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('enrollmentdate', models.DateField()),
            ],
        ),
    ]
